language: node_js

node_js:
  - "lts/*"

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install -q

script:
  - npm run tslint
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push
  on:
    branch:
      - master
